version: '3.7'

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      # - /app/node_modules
    ports:
      - 3000:3000
    command: bash -c "npm install && npm run start"
    restart: always
    networks:
      - app
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      # - /app/node_modules
    ports:
      - 8000:8000
    command: bash -c "npm install && npm run dev"
    depends_on:
      - postgres
    restart: always
    networks:
      - app
  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - ./server/.env
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres   
      POSTGRES_DB: vkr
    ports:
      - 5432:5432
    restart: always
    networks:
      - app
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    restart: always
    networks:
      - app
networks: 
  app:
    driver: 'bridge'